#spring.application.name=account-service

server:
  port: 8081

spring:
  application:
    name: account-service

  datasource:
    url: jdbc:postgresql://localhost:5432/account_db
    username: postgres
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  Jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true